# Generated by Django 2.2 on 2019-08-31 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='rating',
            new_name='avg_rating',
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_visited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Place')),
            ],
        ),
    ]
