# Generated by Django 2.2 on 2019-08-31 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190901_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='avg_rating',
        ),
    ]
