# Generated by Django 2.2 on 2019-08-31 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_place_avg_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.ImageField(default='/static/img/logo.png', upload_to='images/'),
        ),
    ]
